INSERT INTO fund_info VALUES (1, '000578', '上海仲p', 1);
INSERT INTO fund_info VALUES (2, '160216', '国泰商品', 1);
INSERT INTO fund_info VALUES (3, '001518', '万家瑞兴', 2);
INSERT INTO fund_info VALUES (4, '020003', '国泰金龙行业精选', 3);
INSERT INTO fund_info VALUES (5, '001272', '兴业聚利灵活配置混合', 3);

INSERT INTO fund_managers VALUES (1, '', '王力宏', 'FM', NULL, NULL, '我是一名基金经理<br>');
INSERT INTO fund_managers VALUES (2, 'jack', '周杰', 'FM', NULL, NULL, '听故事发看看<br>');

INSERT INTO grouptree VALUES (1, 24);
INSERT INTO grouptree VALUES (1, 70);
INSERT INTO grouptree VALUES (1, 80);
INSERT INTO grouptree VALUES (1, 81);
INSERT INTO grouptree VALUES (1, 82);
INSERT INTO grouptree VALUES (1, 47);
INSERT INTO grouptree VALUES (1, 49);
INSERT INTO grouptree VALUES (1, 50);
INSERT INTO grouptree VALUES (1, 52);
INSERT INTO grouptree VALUES (1, 53);
INSERT INTO grouptree VALUES (1, 56);
INSERT INTO grouptree VALUES (1, 25);
INSERT INTO grouptree VALUES (1, 14);
INSERT INTO grouptree VALUES (1, 11);
INSERT INTO grouptree VALUES (1, 13);
INSERT INTO grouptree VALUES (1, 15);
INSERT INTO grouptree VALUES (1, 16);
INSERT INTO grouptree VALUES (1, 20);
INSERT INTO grouptree VALUES (1, 21);
INSERT INTO grouptree VALUES (1, 22);
INSERT INTO grouptree VALUES (1, 23);
INSERT INTO grouptree VALUES (1, 10);
INSERT INTO grouptree VALUES (2, 15);
INSERT INTO grouptree VALUES (2, 70);
INSERT INTO grouptree VALUES (2, 16);
INSERT INTO grouptree VALUES (2, 14);
INSERT INTO grouptree VALUES (2, 13);
INSERT INTO grouptree VALUES (2, 11);
INSERT INTO grouptree VALUES (2, 10);
INSERT INTO grouptree VALUES (16, 1);
INSERT INTO grouptree VALUES (16, 12);
INSERT INTO grouptree VALUES (37, 70);
INSERT INTO grouptree VALUES (37, 80);
INSERT INTO grouptree VALUES (37, 81);
INSERT INTO grouptree VALUES (37, 82);
INSERT INTO grouptree VALUES (37, 47);
INSERT INTO grouptree VALUES (37, 49);
INSERT INTO grouptree VALUES (37, 50);
INSERT INTO grouptree VALUES (37, 52);
INSERT INTO grouptree VALUES (37, 53);
INSERT INTO grouptree VALUES (37, 25);
INSERT INTO grouptree VALUES (37, 24);
INSERT INTO grouptree VALUES (37, 23);
INSERT INTO grouptree VALUES (37, 10);
INSERT INTO grouptree VALUES (37, 11);
INSERT INTO grouptree VALUES (37, 13);
INSERT INTO grouptree VALUES (37, 14);
INSERT INTO grouptree VALUES (37, 15);
INSERT INTO grouptree VALUES (37, 16);
INSERT INTO grouptree VALUES (37, 20);
INSERT INTO grouptree VALUES (37, 21);
INSERT INTO grouptree VALUES (37, 22);
INSERT INTO grouptree VALUES (37, 56);

INSERT INTO guser VALUES (1, '1', NULL, '管理员', 'PIDCard', 'sqegom1@126.com', 'admin', NULL, NULL, 'M', 'SQE12001', '430902198710015578', '0', 'SINGLE', '86(957)6879-123', 'c4ca4238a0b923820dcc509a6f75849b', '10', 'QUALIFIED', '0');
INSERT INTO guser VALUES (2, '1', NULL, '李磊', 'PIDCard', 'sqegom4@126.com', 'li', NULL, NULL, 'F', 'SQE12002', '426655995656322112', '0', 'SINGLE', '86(21)3387-4356', 'c4ca4238a0b923820dcc509a6f75849b', '12', 'QUALIFIED', '0');
INSERT INTO guser VALUES (15, '1', NULL, '欧阳', 'PASSPORT', 'sqegom2@126.com', 'ole', NULL, NULL, 'F', 'SQE13015', '1564651616', '0', 'MARRIED', '86(21)1760-1860', 'c4ca4238a0b923820dcc509a6f75849b', '16', 'QUALIFIED', '1');

INSERT INTO ico VALUES (1, 'fa-user', NULL);
INSERT INTO ico VALUES (2, 'fa-lock', NULL);
INSERT INTO ico VALUES (3, 'm-icon-swapright m-icon-white', NULL);
INSERT INTO ico VALUES (4, 'fa-american-sign-language-interpreting', NULL);
INSERT INTO ico VALUES (5, 'fa-asl-interpreting', NULL);
INSERT INTO ico VALUES (6, 'fa-assistive-listening-systems', NULL);
INSERT INTO ico VALUES (7, 'fa-audio-description', NULL);
INSERT INTO ico VALUES (8, 'fa-blind', NULL);
INSERT INTO ico VALUES (9, 'fa-braille', NULL);
INSERT INTO ico VALUES (10, 'fa-deaf', NULL);
INSERT INTO ico VALUES (11, 'fa-deafness', NULL);
INSERT INTO ico VALUES (12, 'fa-envira', NULL);
INSERT INTO ico VALUES (13, 'fa-fa', NULL);
INSERT INTO ico VALUES (14, 'fa-first-order', NULL);
INSERT INTO ico VALUES (15, 'fa-font-awesome', NULL);
INSERT INTO ico VALUES (16, 'fa-gitlab', NULL);
INSERT INTO ico VALUES (17, 'fa-glide', NULL);
INSERT INTO ico VALUES (18, 'fa-glide-g', NULL);
INSERT INTO ico VALUES (19, 'fa-google-plus-circle', NULL);
INSERT INTO ico VALUES (20, 'fa-google-plus-official', NULL);
INSERT INTO ico VALUES (21, 'fa-hard-of-hearing', NULL);
INSERT INTO ico VALUES (22, 'fa-instagram', NULL);
INSERT INTO ico VALUES (23, 'fa-low-vision', NULL);
INSERT INTO ico VALUES (24, 'fa-pied-piper', NULL);
INSERT INTO ico VALUES (25, 'fa-question-circle-o', NULL);
INSERT INTO ico VALUES (26, 'fa-sign-language', NULL);
INSERT INTO ico VALUES (27, 'fa-signing', NULL);
INSERT INTO ico VALUES (28, 'fa-snapchat', NULL);
INSERT INTO ico VALUES (29, 'fa-snapchat-ghost', NULL);
INSERT INTO ico VALUES (30, 'fa-snapchat-square', NULL);
INSERT INTO ico VALUES (31, 'fa-themeisle', NULL);
INSERT INTO ico VALUES (32, 'fa-universal-access', NULL);
INSERT INTO ico VALUES (33, 'fa-viadeo', NULL);
INSERT INTO ico VALUES (34, 'fa-viadeo-square', NULL);
INSERT INTO ico VALUES (35, 'fa-volume-control-phone', NULL);
INSERT INTO ico VALUES (36, 'fa-wheelchair-alt', NULL);
INSERT INTO ico VALUES (37, 'fa-wpbeginner', NULL);
INSERT INTO ico VALUES (38, 'fa-wpforms', NULL);
INSERT INTO ico VALUES (39, 'fa-yoast', NULL);
INSERT INTO ico VALUES (40, 'fa-adjust', NULL);
INSERT INTO ico VALUES (41, 'fa-american-sign-language-interpreting', NULL);
INSERT INTO ico VALUES (42, 'fa-anchor', NULL);
INSERT INTO ico VALUES (43, 'fa-archive', NULL);
INSERT INTO ico VALUES (44, 'fa-area-chart', NULL);
INSERT INTO ico VALUES (45, 'fa-arrows', NULL);
INSERT INTO ico VALUES (46, 'fa-arrows-h', NULL);
INSERT INTO ico VALUES (47, 'fa-arrows-v', NULL);
INSERT INTO ico VALUES (48, 'fa-asl-interpreting', NULL);
INSERT INTO ico VALUES (49, 'fa-assistive-listening-systems', NULL);
INSERT INTO ico VALUES (50, 'fa-asterisk', NULL);
INSERT INTO ico VALUES (51, 'fa-at', NULL);
INSERT INTO ico VALUES (52, 'fa-audio-description', NULL);
INSERT INTO ico VALUES (53, 'fa-automobile', NULL);
INSERT INTO ico VALUES (54, 'fa-balance-scale', NULL);
INSERT INTO ico VALUES (55, 'fa-ban', NULL);
INSERT INTO ico VALUES (56, 'fa-bank', NULL);
INSERT INTO ico VALUES (57, 'fa-bar-chart', NULL);
INSERT INTO ico VALUES (58, 'fa-bar-chart-o', NULL);
INSERT INTO ico VALUES (59, 'fa-barcode', NULL);
INSERT INTO ico VALUES (60, 'fa-bars', NULL);
INSERT INTO ico VALUES (61, 'fa-battery-0', NULL);
INSERT INTO ico VALUES (62, 'fa-battery-1', NULL);
INSERT INTO ico VALUES (63, 'fa-battery-2', NULL);
INSERT INTO ico VALUES (64, 'fa-battery-3', NULL);
INSERT INTO ico VALUES (65, 'fa-battery-4', NULL);
INSERT INTO ico VALUES (66, 'fa-battery-empty', NULL);
INSERT INTO ico VALUES (67, 'fa-battery-full', NULL);
INSERT INTO ico VALUES (68, 'fa-battery-half', NULL);
INSERT INTO ico VALUES (69, 'fa-battery-quarter', NULL);
INSERT INTO ico VALUES (70, 'fa-battery-three-quarters', NULL);
INSERT INTO ico VALUES (71, 'fa-bed', NULL);
INSERT INTO ico VALUES (72, 'fa-beer', NULL);
INSERT INTO ico VALUES (73, 'fa-bell', NULL);
INSERT INTO ico VALUES (74, 'fa-bell-o', NULL);
INSERT INTO ico VALUES (75, 'fa-bell-slash', NULL);
INSERT INTO ico VALUES (76, 'fa-bell-slash-o', NULL);
INSERT INTO ico VALUES (77, 'fa-bicycle', NULL);
INSERT INTO ico VALUES (78, 'fa-binoculars', NULL);
INSERT INTO ico VALUES (79, 'fa-birthday-cake', NULL);
INSERT INTO ico VALUES (80, 'fa-blind', NULL);
INSERT INTO ico VALUES (81, 'fa-bluetooth', NULL);
INSERT INTO ico VALUES (82, 'fa-bluetooth-b', NULL);
INSERT INTO ico VALUES (83, 'fa-bolt', NULL);
INSERT INTO ico VALUES (84, 'fa-bomb', NULL);
INSERT INTO ico VALUES (85, 'fa-book', NULL);
INSERT INTO ico VALUES (86, 'fa-bookmark', NULL);
INSERT INTO ico VALUES (87, 'fa-bookmark-o', NULL);
INSERT INTO ico VALUES (88, 'fa-braille', NULL);
INSERT INTO ico VALUES (89, 'fa-briefcase', NULL);
INSERT INTO ico VALUES (90, 'fa-bug', NULL);
INSERT INTO ico VALUES (91, 'fa-building', NULL);
INSERT INTO ico VALUES (92, 'fa-building-o', NULL);
INSERT INTO ico VALUES (93, 'fa-bullhorn', NULL);
INSERT INTO ico VALUES (94, 'fa-bullseye', NULL);
INSERT INTO ico VALUES (95, 'fa-bus', NULL);
INSERT INTO ico VALUES (96, 'fa-cab', NULL);
INSERT INTO ico VALUES (97, 'fa-calculator', NULL);
INSERT INTO ico VALUES (98, 'fa-calendar', NULL);
INSERT INTO ico VALUES (99, 'fa-calendar-check-o', NULL);
INSERT INTO ico VALUES (100, 'fa-calendar-minus-o', NULL);
INSERT INTO ico VALUES (101, 'fa-calendar-o', NULL);
INSERT INTO ico VALUES (102, 'fa-calendar-plus-o', NULL);
INSERT INTO ico VALUES (103, 'fa-calendar-times-o', NULL);
INSERT INTO ico VALUES (104, 'fa-camera', NULL);
INSERT INTO ico VALUES (105, 'fa-camera-retro', NULL);
INSERT INTO ico VALUES (106, 'fa-car', NULL);
INSERT INTO ico VALUES (107, 'fa-caret-square-o-down', NULL);
INSERT INTO ico VALUES (108, 'fa-caret-square-o-left', NULL);
INSERT INTO ico VALUES (109, 'fa-caret-square-o-right', NULL);
INSERT INTO ico VALUES (110, 'fa-caret-square-o-up', NULL);
INSERT INTO ico VALUES (111, 'fa-cart-arrow-down', NULL);
INSERT INTO ico VALUES (112, 'fa-cart-plus', NULL);
INSERT INTO ico VALUES (113, 'fa-cc', NULL);
INSERT INTO ico VALUES (114, 'fa-certificate', NULL);
INSERT INTO ico VALUES (115, 'fa-check', NULL);
INSERT INTO ico VALUES (116, 'fa-check-circle', NULL);
INSERT INTO ico VALUES (117, 'fa-check-circle-o', NULL);
INSERT INTO ico VALUES (118, 'fa-check-square', NULL);
INSERT INTO ico VALUES (119, 'fa-check-square-o', NULL);
INSERT INTO ico VALUES (120, 'fa-child', NULL);
INSERT INTO ico VALUES (121, 'fa-circle', NULL);
INSERT INTO ico VALUES (122, 'fa-circle-o', NULL);
INSERT INTO ico VALUES (123, 'fa-circle-o-notch', NULL);
INSERT INTO ico VALUES (124, 'fa-circle-thin', NULL);
INSERT INTO ico VALUES (125, 'fa-clock-o', NULL);
INSERT INTO ico VALUES (126, 'fa-clone', NULL);
INSERT INTO ico VALUES (127, 'fa-close', NULL);
INSERT INTO ico VALUES (128, 'fa-cloud', NULL);
INSERT INTO ico VALUES (129, 'fa-cloud-download', NULL);
INSERT INTO ico VALUES (130, 'fa-cloud-upload', NULL);
INSERT INTO ico VALUES (131, 'fa-code', NULL);
INSERT INTO ico VALUES (132, 'fa-code-fork', NULL);
INSERT INTO ico VALUES (133, 'fa-coffee', NULL);
INSERT INTO ico VALUES (134, 'fa-cog', NULL);
INSERT INTO ico VALUES (135, 'fa-cogs', NULL);
INSERT INTO ico VALUES (136, 'fa-comment', NULL);
INSERT INTO ico VALUES (137, 'fa-comment-o', NULL);
INSERT INTO ico VALUES (138, 'fa-commenting', NULL);
INSERT INTO ico VALUES (139, 'fa-commenting-o', NULL);
INSERT INTO ico VALUES (140, 'fa-comments', NULL);
INSERT INTO ico VALUES (141, 'fa-comments-o', NULL);
INSERT INTO ico VALUES (142, 'fa-compass', NULL);
INSERT INTO ico VALUES (143, 'fa-copyright', NULL);
INSERT INTO ico VALUES (144, 'fa-creative-commons', NULL);
INSERT INTO ico VALUES (145, 'fa-credit-card', NULL);
INSERT INTO ico VALUES (146, 'fa-credit-card-alt', NULL);
INSERT INTO ico VALUES (147, 'fa-crop', NULL);
INSERT INTO ico VALUES (148, 'fa-crosshairs', NULL);
INSERT INTO ico VALUES (149, 'fa-cube', NULL);
INSERT INTO ico VALUES (150, 'fa-cubes', NULL);
INSERT INTO ico VALUES (151, 'fa-cutlery', NULL);
INSERT INTO ico VALUES (152, 'fa-dashboard', NULL);
INSERT INTO ico VALUES (153, 'fa-database', NULL);
INSERT INTO ico VALUES (154, 'fa-deaf', NULL);
INSERT INTO ico VALUES (155, 'fa-deafness', NULL);
INSERT INTO ico VALUES (156, 'fa-desktop', NULL);
INSERT INTO ico VALUES (157, 'fa-diamond', NULL);
INSERT INTO ico VALUES (158, 'fa-dot-circle-o', NULL);
INSERT INTO ico VALUES (159, 'fa-download', NULL);
INSERT INTO ico VALUES (160, 'fa-edit', NULL);
INSERT INTO ico VALUES (161, 'fa-ellipsis-h', NULL);
INSERT INTO ico VALUES (162, 'fa-ellipsis-v', NULL);
INSERT INTO ico VALUES (163, 'fa-envelope', NULL);
INSERT INTO ico VALUES (164, 'fa-envelope-o', NULL);
INSERT INTO ico VALUES (165, 'fa-envelope-square', NULL);
INSERT INTO ico VALUES (166, 'fa-eraser', NULL);
INSERT INTO ico VALUES (167, 'fa-exchange', NULL);
INSERT INTO ico VALUES (168, 'fa-exclamation', NULL);
INSERT INTO ico VALUES (169, 'fa-exclamation-circle', NULL);
INSERT INTO ico VALUES (170, 'fa-exclamation-triangle', NULL);
INSERT INTO ico VALUES (171, 'fa-external-link', NULL);
INSERT INTO ico VALUES (172, 'fa-external-link-square', NULL);
INSERT INTO ico VALUES (173, 'fa-eye', NULL);
INSERT INTO ico VALUES (174, 'fa-eye-slash', NULL);
INSERT INTO ico VALUES (175, 'fa-eyedropper', NULL);
INSERT INTO ico VALUES (176, 'fa-fax', NULL);
INSERT INTO ico VALUES (177, 'fa-feed', NULL);
INSERT INTO ico VALUES (178, 'fa-female', NULL);
INSERT INTO ico VALUES (179, 'fa-fighter-jet', NULL);
INSERT INTO ico VALUES (180, 'fa-file-archive-o', NULL);
INSERT INTO ico VALUES (181, 'fa-file-audio-o', NULL);
INSERT INTO ico VALUES (182, 'fa-file-code-o', NULL);
INSERT INTO ico VALUES (183, 'fa-file-excel-o', NULL);
INSERT INTO ico VALUES (184, 'fa-file-image-o', NULL);
INSERT INTO ico VALUES (185, 'fa-file-movie-o', NULL);
INSERT INTO ico VALUES (186, 'fa-file-pdf-o', NULL);
INSERT INTO ico VALUES (187, 'fa-file-photo-o', NULL);
INSERT INTO ico VALUES (188, 'fa-file-picture-o', NULL);
INSERT INTO ico VALUES (189, 'fa-file-powerpoint-o', NULL);
INSERT INTO ico VALUES (190, 'fa-file-sound-o', NULL);
INSERT INTO ico VALUES (191, 'fa-file-video-o', NULL);
INSERT INTO ico VALUES (192, 'fa-file-word-o', NULL);
INSERT INTO ico VALUES (193, 'fa-file-zip-o', NULL);
INSERT INTO ico VALUES (194, 'fa-film', NULL);
INSERT INTO ico VALUES (195, 'fa-filter', NULL);
INSERT INTO ico VALUES (196, 'fa-fire', NULL);
INSERT INTO ico VALUES (197, 'fa-fire-extinguisher', NULL);
INSERT INTO ico VALUES (198, 'fa-flag', NULL);
INSERT INTO ico VALUES (199, 'fa-flag-checkered', NULL);
INSERT INTO ico VALUES (200, 'fa-flag-o', NULL);
INSERT INTO ico VALUES (201, 'fa-flash', NULL);
INSERT INTO ico VALUES (202, 'fa-flask', NULL);
INSERT INTO ico VALUES (203, 'fa-folder', NULL);
INSERT INTO ico VALUES (204, 'fa-folder-o', NULL);
INSERT INTO ico VALUES (205, 'fa-folder-open', NULL);
INSERT INTO ico VALUES (206, 'fa-folder-open-o', NULL);
INSERT INTO ico VALUES (207, 'fa-frown-o', NULL);
INSERT INTO ico VALUES (208, 'fa-futbol-o', NULL);
INSERT INTO ico VALUES (209, 'fa-gamepad', NULL);
INSERT INTO ico VALUES (210, 'fa-gavel', NULL);
INSERT INTO ico VALUES (211, 'fa-gear', NULL);
INSERT INTO ico VALUES (212, 'fa-gears', NULL);
INSERT INTO ico VALUES (213, 'fa-gift', NULL);
INSERT INTO ico VALUES (214, 'fa-glass', NULL);
INSERT INTO ico VALUES (215, 'fa-globe', NULL);
INSERT INTO ico VALUES (216, 'fa-graduation-cap', NULL);
INSERT INTO ico VALUES (217, 'fa-group', NULL);
INSERT INTO ico VALUES (218, 'fa-hand-grab-o', NULL);
INSERT INTO ico VALUES (219, 'fa-hand-lizard-o', NULL);
INSERT INTO ico VALUES (220, 'fa-hand-paper-o', NULL);
INSERT INTO ico VALUES (221, 'fa-hand-peace-o', NULL);
INSERT INTO ico VALUES (222, 'fa-hand-pointer-o', NULL);
INSERT INTO ico VALUES (223, 'fa-hand-rock-o', NULL);
INSERT INTO ico VALUES (224, 'fa-hand-scissors-o', NULL);
INSERT INTO ico VALUES (225, 'fa-hand-spock-o', NULL);
INSERT INTO ico VALUES (226, 'fa-hand-stop-o', NULL);
INSERT INTO ico VALUES (227, 'fa-hard-of-hearing', NULL);
INSERT INTO ico VALUES (228, 'fa-hashtag', NULL);
INSERT INTO ico VALUES (229, 'fa-hdd-o', NULL);
INSERT INTO ico VALUES (230, 'fa-headphones', NULL);
INSERT INTO ico VALUES (231, 'fa-heart', NULL);
INSERT INTO ico VALUES (232, 'fa-heart-o', NULL);
INSERT INTO ico VALUES (233, 'fa-heartbeat', NULL);
INSERT INTO ico VALUES (234, 'fa-history', NULL);
INSERT INTO ico VALUES (235, 'fa-home', NULL);
INSERT INTO ico VALUES (236, 'fa-hotel', NULL);
INSERT INTO ico VALUES (237, 'fa-hourglass', NULL);
INSERT INTO ico VALUES (238, 'fa-hourglass-1', NULL);
INSERT INTO ico VALUES (239, 'fa-hourglass-2', NULL);
INSERT INTO ico VALUES (240, 'fa-hourglass-3', NULL);
INSERT INTO ico VALUES (241, 'fa-hourglass-end', NULL);
INSERT INTO ico VALUES (242, 'fa-hourglass-half', NULL);
INSERT INTO ico VALUES (243, 'fa-hourglass-o', NULL);
INSERT INTO ico VALUES (244, 'fa-hourglass-start', NULL);
INSERT INTO ico VALUES (245, 'fa-i-cursor', NULL);
INSERT INTO ico VALUES (246, 'fa-image', NULL);
INSERT INTO ico VALUES (247, 'fa-inbox', NULL);
INSERT INTO ico VALUES (248, 'fa-industry', NULL);
INSERT INTO ico VALUES (249, 'fa-info', NULL);
INSERT INTO ico VALUES (250, 'fa-info-circle', NULL);
INSERT INTO ico VALUES (251, 'fa-institution', NULL);
INSERT INTO ico VALUES (252, 'fa-key', NULL);
INSERT INTO ico VALUES (253, 'fa-keyboard-o', NULL);
INSERT INTO ico VALUES (254, 'fa-language', NULL);
INSERT INTO ico VALUES (255, 'fa-laptop', NULL);
INSERT INTO ico VALUES (256, 'fa-leaf', NULL);
INSERT INTO ico VALUES (257, 'fa-legal', NULL);
INSERT INTO ico VALUES (258, 'fa-lemon-o', NULL);
INSERT INTO ico VALUES (259, 'fa-level-down', NULL);
INSERT INTO ico VALUES (260, 'fa-level-up', NULL);
INSERT INTO ico VALUES (261, 'fa-life-bouy', NULL);
INSERT INTO ico VALUES (262, 'fa-life-buoy', NULL);
INSERT INTO ico VALUES (263, 'fa-life-ring', NULL);
INSERT INTO ico VALUES (264, 'fa-life-saver', NULL);
INSERT INTO ico VALUES (265, 'fa-lightbulb-o', NULL);
INSERT INTO ico VALUES (266, 'fa-line-chart', NULL);
INSERT INTO ico VALUES (267, 'fa-location-arrow', NULL);
INSERT INTO ico VALUES (268, 'fa-lock', NULL);
INSERT INTO ico VALUES (269, 'fa-low-vision', NULL);
INSERT INTO ico VALUES (270, 'fa-magic', NULL);
INSERT INTO ico VALUES (271, 'fa-magnet', NULL);
INSERT INTO ico VALUES (272, 'fa-mail-forward', NULL);
INSERT INTO ico VALUES (273, 'fa-mail-reply', NULL);
INSERT INTO ico VALUES (274, 'fa-mail-reply-all', NULL);
INSERT INTO ico VALUES (275, 'fa-male', NULL);
INSERT INTO ico VALUES (276, 'fa-map', NULL);
INSERT INTO ico VALUES (277, 'fa-map-marker', NULL);
INSERT INTO ico VALUES (278, 'fa-map-o', NULL);
INSERT INTO ico VALUES (279, 'fa-map-pin', NULL);
INSERT INTO ico VALUES (280, 'fa-map-signs', NULL);
INSERT INTO ico VALUES (281, 'fa-meh-o', NULL);
INSERT INTO ico VALUES (282, 'fa-microphone', NULL);
INSERT INTO ico VALUES (283, 'fa-microphone-slash', NULL);
INSERT INTO ico VALUES (284, 'fa-minus', NULL);
INSERT INTO ico VALUES (285, 'fa-minus-circle', NULL);
INSERT INTO ico VALUES (286, 'fa-minus-square', NULL);
INSERT INTO ico VALUES (287, 'fa-minus-square-o', NULL);
INSERT INTO ico VALUES (288, 'fa-mobile', NULL);
INSERT INTO ico VALUES (289, 'fa-mobile-phone', NULL);
INSERT INTO ico VALUES (290, 'fa-money', NULL);
INSERT INTO ico VALUES (291, 'fa-moon-o', NULL);
INSERT INTO ico VALUES (292, 'fa-mortar-board', NULL);
INSERT INTO ico VALUES (293, 'fa-motorcycle', NULL);
INSERT INTO ico VALUES (294, 'fa-mouse-pointer', NULL);
INSERT INTO ico VALUES (295, 'fa-music', NULL);
INSERT INTO ico VALUES (296, 'fa-navicon', NULL);
INSERT INTO ico VALUES (297, 'fa-newspaper-o', NULL);
INSERT INTO ico VALUES (298, 'fa-object-group', NULL);
INSERT INTO ico VALUES (299, 'fa-object-ungroup', NULL);
INSERT INTO ico VALUES (300, 'fa-paint-brush', NULL);
INSERT INTO ico VALUES (301, 'fa-paper-plane', NULL);
INSERT INTO ico VALUES (302, 'fa-paper-plane-o', NULL);
INSERT INTO ico VALUES (303, 'fa-paw', NULL);
INSERT INTO ico VALUES (304, 'fa-pencil', NULL);
INSERT INTO ico VALUES (305, 'fa-pencil-square', NULL);
INSERT INTO ico VALUES (306, 'fa-pencil-square-o', NULL);
INSERT INTO ico VALUES (307, 'fa-percent', NULL);
INSERT INTO ico VALUES (308, 'fa-phone', NULL);
INSERT INTO ico VALUES (309, 'fa-phone-square', NULL);
INSERT INTO ico VALUES (310, 'fa-photo', NULL);
INSERT INTO ico VALUES (311, 'fa-picture-o', NULL);
INSERT INTO ico VALUES (312, 'fa-pie-chart', NULL);
INSERT INTO ico VALUES (313, 'fa-plane', NULL);
INSERT INTO ico VALUES (314, 'fa-plug', NULL);
INSERT INTO ico VALUES (315, 'fa-plus', NULL);
INSERT INTO ico VALUES (316, 'fa-plus-circle', NULL);
INSERT INTO ico VALUES (317, 'fa-plus-square', NULL);
INSERT INTO ico VALUES (318, 'fa-plus-square-o', NULL);
INSERT INTO ico VALUES (319, 'fa-power-off', NULL);
INSERT INTO ico VALUES (320, 'fa-print', NULL);
INSERT INTO ico VALUES (321, 'fa-puzzle-piece', NULL);
INSERT INTO ico VALUES (322, 'fa-qrcode', NULL);
INSERT INTO ico VALUES (323, 'fa-question', NULL);
INSERT INTO ico VALUES (324, 'fa-question-circle', NULL);
INSERT INTO ico VALUES (325, 'fa-question-circle-o', NULL);
INSERT INTO ico VALUES (326, 'fa-quote-left', NULL);
INSERT INTO ico VALUES (327, 'fa-quote-right', NULL);
INSERT INTO ico VALUES (328, 'fa-random', NULL);
INSERT INTO ico VALUES (329, 'fa-recycle', NULL);
INSERT INTO ico VALUES (330, 'fa-refresh', NULL);
INSERT INTO ico VALUES (331, 'fa-registered', NULL);
INSERT INTO ico VALUES (332, 'fa-remove', NULL);
INSERT INTO ico VALUES (333, 'fa-reorder', NULL);
INSERT INTO ico VALUES (334, 'fa-reply', NULL);
INSERT INTO ico VALUES (335, 'fa-reply-all', NULL);
INSERT INTO ico VALUES (336, 'fa-retweet', NULL);
INSERT INTO ico VALUES (337, 'fa-road', NULL);
INSERT INTO ico VALUES (338, 'fa-rocket', NULL);
INSERT INTO ico VALUES (339, 'fa-rss', NULL);
INSERT INTO ico VALUES (340, 'fa-rss-square', NULL);
INSERT INTO ico VALUES (341, 'fa-search', NULL);
INSERT INTO ico VALUES (342, 'fa-search-minus', NULL);
INSERT INTO ico VALUES (343, 'fa-search-plus', NULL);
INSERT INTO ico VALUES (344, 'fa-send', NULL);
INSERT INTO ico VALUES (345, 'fa-send-o', NULL);
INSERT INTO ico VALUES (346, 'fa-server', NULL);
INSERT INTO ico VALUES (347, 'fa-share', NULL);
INSERT INTO ico VALUES (348, 'fa-share-alt', NULL);
INSERT INTO ico VALUES (349, 'fa-share-alt-square', NULL);
INSERT INTO ico VALUES (350, 'fa-share-square', NULL);
INSERT INTO ico VALUES (351, 'fa-share-square-o', NULL);
INSERT INTO ico VALUES (352, 'fa-shield', NULL);
INSERT INTO ico VALUES (353, 'fa-ship', NULL);
INSERT INTO ico VALUES (354, 'fa-shopping-bag', NULL);
INSERT INTO ico VALUES (355, 'fa-shopping-basket', NULL);
INSERT INTO ico VALUES (356, 'fa-shopping-cart', NULL);
INSERT INTO ico VALUES (357, 'fa-sign-in', NULL);
INSERT INTO ico VALUES (358, 'fa-sign-language', NULL);
INSERT INTO ico VALUES (359, 'fa-sign-out', NULL);
INSERT INTO ico VALUES (360, 'fa-signal', NULL);
INSERT INTO ico VALUES (361, 'fa-signing', NULL);
INSERT INTO ico VALUES (362, 'fa-sitemap', NULL);
INSERT INTO ico VALUES (363, 'fa-sliders', NULL);
INSERT INTO ico VALUES (364, 'fa-smile-o', NULL);
INSERT INTO ico VALUES (365, 'fa-soccer-ball-o', NULL);
INSERT INTO ico VALUES (366, 'fa-sort', NULL);
INSERT INTO ico VALUES (367, 'fa-sort-alpha-asc', NULL);
INSERT INTO ico VALUES (368, 'fa-sort-alpha-desc', NULL);
INSERT INTO ico VALUES (369, 'fa-sort-amount-asc', NULL);
INSERT INTO ico VALUES (370, 'fa-sort-amount-desc', NULL);
INSERT INTO ico VALUES (371, 'fa-sort-asc', NULL);
INSERT INTO ico VALUES (372, 'fa-sort-desc', NULL);
INSERT INTO ico VALUES (373, 'fa-sort-down', NULL);
INSERT INTO ico VALUES (374, 'fa-sort-numeric-asc', NULL);
INSERT INTO ico VALUES (375, 'fa-sort-numeric-desc', NULL);
INSERT INTO ico VALUES (376, 'fa-sort-up', NULL);
INSERT INTO ico VALUES (377, 'fa-space-shuttle', NULL);
INSERT INTO ico VALUES (378, 'fa-spinner', NULL);
INSERT INTO ico VALUES (379, 'fa-spoon', NULL);
INSERT INTO ico VALUES (380, 'fa-square', NULL);
INSERT INTO ico VALUES (381, 'fa-square-o', NULL);
INSERT INTO ico VALUES (382, 'fa-star', NULL);
INSERT INTO ico VALUES (383, 'fa-star-half', NULL);
INSERT INTO ico VALUES (384, 'fa-star-half-empty', NULL);
INSERT INTO ico VALUES (385, 'fa-star-half-full', NULL);
INSERT INTO ico VALUES (386, 'fa-star-half-o', NULL);
INSERT INTO ico VALUES (387, 'fa-star-o', NULL);
INSERT INTO ico VALUES (388, 'fa-sticky-note', NULL);
INSERT INTO ico VALUES (389, 'fa-sticky-note-o', NULL);
INSERT INTO ico VALUES (390, 'fa-street-view', NULL);
INSERT INTO ico VALUES (391, 'fa-suitcase', NULL);
INSERT INTO ico VALUES (392, 'fa-sun-o', NULL);
INSERT INTO ico VALUES (393, 'fa-support', NULL);
INSERT INTO ico VALUES (394, 'fa-tablet', NULL);
INSERT INTO ico VALUES (395, 'fa-tachometer', NULL);
INSERT INTO ico VALUES (396, 'fa-tag', NULL);
INSERT INTO ico VALUES (397, 'fa-tags', NULL);
INSERT INTO ico VALUES (398, 'fa-tasks', NULL);
INSERT INTO ico VALUES (399, 'fa-taxi', NULL);
INSERT INTO ico VALUES (400, 'fa-television', NULL);
INSERT INTO ico VALUES (401, 'fa-terminal', NULL);
INSERT INTO ico VALUES (402, 'fa-thumb-tack', NULL);
INSERT INTO ico VALUES (403, 'fa-thumbs-down', NULL);
INSERT INTO ico VALUES (404, 'fa-thumbs-o-down', NULL);
INSERT INTO ico VALUES (405, 'fa-thumbs-o-up', NULL);
INSERT INTO ico VALUES (406, 'fa-thumbs-up', NULL);
INSERT INTO ico VALUES (407, 'fa-ticket', NULL);
INSERT INTO ico VALUES (408, 'fa-times', NULL);
INSERT INTO ico VALUES (409, 'fa-times-circle', NULL);
INSERT INTO ico VALUES (410, 'fa-times-circle-o', NULL);
INSERT INTO ico VALUES (411, 'fa-tint', NULL);
INSERT INTO ico VALUES (412, 'fa-toggle-down', NULL);
INSERT INTO ico VALUES (413, 'fa-toggle-left', NULL);
INSERT INTO ico VALUES (414, 'fa-toggle-off', NULL);
INSERT INTO ico VALUES (415, 'fa-toggle-on', NULL);
INSERT INTO ico VALUES (416, 'fa-toggle-right', NULL);
INSERT INTO ico VALUES (417, 'fa-toggle-up', NULL);
INSERT INTO ico VALUES (418, 'fa-trademark', NULL);
INSERT INTO ico VALUES (419, 'fa-trash', NULL);
INSERT INTO ico VALUES (420, 'fa-trash-o', NULL);
INSERT INTO ico VALUES (421, 'fa-tree', NULL);
INSERT INTO ico VALUES (422, 'fa-trophy', NULL);
INSERT INTO ico VALUES (423, 'fa-truck', NULL);
INSERT INTO ico VALUES (424, 'fa-tty', NULL);
INSERT INTO ico VALUES (425, 'fa-tv', NULL);
INSERT INTO ico VALUES (426, 'fa-umbrella', NULL);
INSERT INTO ico VALUES (427, 'fa-universal-access', NULL);
INSERT INTO ico VALUES (428, 'fa-university', NULL);
INSERT INTO ico VALUES (429, 'fa-unlock', NULL);
INSERT INTO ico VALUES (430, 'fa-unlock-alt', NULL);
INSERT INTO ico VALUES (431, 'fa-unsorted', NULL);
INSERT INTO ico VALUES (432, 'fa-upload', NULL);
INSERT INTO ico VALUES (433, 'fa-user', NULL);
INSERT INTO ico VALUES (434, 'fa-user-plus', NULL);
INSERT INTO ico VALUES (435, 'fa-user-secret', NULL);
INSERT INTO ico VALUES (436, 'fa-user-times', NULL);
INSERT INTO ico VALUES (437, 'fa-users', NULL);
INSERT INTO ico VALUES (438, 'fa-video-camera', NULL);
INSERT INTO ico VALUES (439, 'fa-volume-control-phone', NULL);
INSERT INTO ico VALUES (440, 'fa-volume-down', NULL);
INSERT INTO ico VALUES (441, 'fa-volume-off', NULL);
INSERT INTO ico VALUES (442, 'fa-volume-up', NULL);
INSERT INTO ico VALUES (443, 'fa-warning', NULL);
INSERT INTO ico VALUES (444, 'fa-wheelchair', NULL);
INSERT INTO ico VALUES (445, 'fa-wheelchair-alt', NULL);
INSERT INTO ico VALUES (446, 'fa-wifi', NULL);
INSERT INTO ico VALUES (447, 'fa-wrench', NULL);
INSERT INTO ico VALUES (448, 'fa-american-sign-language-interpreting', NULL);
INSERT INTO ico VALUES (449, 'fa-asl-interpreting', NULL);
INSERT INTO ico VALUES (450, 'fa-assistive-listening-systems', NULL);
INSERT INTO ico VALUES (451, 'fa-audio-description', NULL);
INSERT INTO ico VALUES (452, 'fa-blind', NULL);
INSERT INTO ico VALUES (453, 'fa-braille', NULL);
INSERT INTO ico VALUES (454, 'fa-cc', NULL);
INSERT INTO ico VALUES (455, 'fa-deaf', NULL);
INSERT INTO ico VALUES (456, 'fa-deafness', NULL);
INSERT INTO ico VALUES (457, 'fa-hard-of-hearing', NULL);
INSERT INTO ico VALUES (458, 'fa-low-vision', NULL);
INSERT INTO ico VALUES (459, 'fa-question-circle-o', NULL);
INSERT INTO ico VALUES (460, 'fa-sign-language', NULL);
INSERT INTO ico VALUES (461, 'fa-signing', NULL);
INSERT INTO ico VALUES (462, 'fa-tty', NULL);
INSERT INTO ico VALUES (463, 'fa-universal-access', NULL);
INSERT INTO ico VALUES (464, 'fa-volume-control-phone', NULL);
INSERT INTO ico VALUES (465, 'fa-wheelchair', NULL);
INSERT INTO ico VALUES (466, 'fa-wheelchair-alt', NULL);
INSERT INTO ico VALUES (467, 'fa-hand-grab-o', NULL);
INSERT INTO ico VALUES (468, 'fa-hand-lizard-o', NULL);
INSERT INTO ico VALUES (469, 'fa-hand-o-down', NULL);
INSERT INTO ico VALUES (470, 'fa-hand-o-left', NULL);
INSERT INTO ico VALUES (471, 'fa-hand-o-right', NULL);
INSERT INTO ico VALUES (472, 'fa-hand-o-up', NULL);
INSERT INTO ico VALUES (473, 'fa-hand-paper-o', NULL);
INSERT INTO ico VALUES (474, 'fa-hand-peace-o', NULL);
INSERT INTO ico VALUES (475, 'fa-hand-pointer-o', NULL);
INSERT INTO ico VALUES (476, 'fa-hand-rock-o', NULL);
INSERT INTO ico VALUES (477, 'fa-hand-scissors-o', NULL);
INSERT INTO ico VALUES (478, 'fa-hand-spock-o', NULL);
INSERT INTO ico VALUES (479, 'fa-hand-stop-o', NULL);
INSERT INTO ico VALUES (480, 'fa-thumbs-down', NULL);
INSERT INTO ico VALUES (481, 'fa-thumbs-o-down', NULL);
INSERT INTO ico VALUES (482, 'fa-thumbs-o-up', NULL);
INSERT INTO ico VALUES (483, 'fa-thumbs-up', NULL);
INSERT INTO ico VALUES (484, 'fa-ambulance', NULL);
INSERT INTO ico VALUES (485, 'fa-automobile', NULL);
INSERT INTO ico VALUES (486, 'fa-bicycle', NULL);
INSERT INTO ico VALUES (487, 'fa-bus', NULL);
INSERT INTO ico VALUES (488, 'fa-cab', NULL);
INSERT INTO ico VALUES (489, 'fa-car', NULL);
INSERT INTO ico VALUES (490, 'fa-fighter-jet', NULL);
INSERT INTO ico VALUES (491, 'fa-motorcycle', NULL);
INSERT INTO ico VALUES (492, 'fa-plane', NULL);
INSERT INTO ico VALUES (493, 'fa-rocket', NULL);
INSERT INTO ico VALUES (494, 'fa-ship', NULL);
INSERT INTO ico VALUES (495, 'fa-space-shuttle', NULL);
INSERT INTO ico VALUES (496, 'fa-subway', NULL);
INSERT INTO ico VALUES (497, 'fa-taxi', NULL);
INSERT INTO ico VALUES (498, 'fa-train', NULL);
INSERT INTO ico VALUES (499, 'fa-truck', NULL);
INSERT INTO ico VALUES (500, 'fa-wheelchair', NULL);
INSERT INTO ico VALUES (501, 'fa-wheelchair-alt', NULL);
INSERT INTO ico VALUES (502, 'fa-genderless', NULL);
INSERT INTO ico VALUES (503, 'fa-intersex', NULL);
INSERT INTO ico VALUES (504, 'fa-mars', NULL);
INSERT INTO ico VALUES (505, 'fa-mars-double', NULL);
INSERT INTO ico VALUES (506, 'fa-mars-stroke', NULL);
INSERT INTO ico VALUES (507, 'fa-mars-stroke-h', NULL);
INSERT INTO ico VALUES (508, 'fa-mars-stroke-v', NULL);
INSERT INTO ico VALUES (509, 'fa-mercury', NULL);
INSERT INTO ico VALUES (510, 'fa-neuter', NULL);
INSERT INTO ico VALUES (511, 'fa-transgender', NULL);
INSERT INTO ico VALUES (512, 'fa-transgender-alt', NULL);
INSERT INTO ico VALUES (513, 'fa-venus', NULL);
INSERT INTO ico VALUES (514, 'fa-venus-double', NULL);
INSERT INTO ico VALUES (515, 'fa-venus-mars', NULL);
INSERT INTO ico VALUES (516, 'fa-file', NULL);
INSERT INTO ico VALUES (517, 'fa-file-archive-o', NULL);
INSERT INTO ico VALUES (518, 'fa-file-audio-o', NULL);
INSERT INTO ico VALUES (519, 'fa-file-code-o', NULL);
INSERT INTO ico VALUES (520, 'fa-file-excel-o', NULL);
INSERT INTO ico VALUES (521, 'fa-file-image-o', NULL);
INSERT INTO ico VALUES (522, 'fa-file-movie-o', NULL);
INSERT INTO ico VALUES (523, 'fa-file-o', NULL);
INSERT INTO ico VALUES (524, 'fa-file-pdf-o', NULL);
INSERT INTO ico VALUES (525, 'fa-file-photo-o', NULL);
INSERT INTO ico VALUES (526, 'fa-file-picture-o', NULL);
INSERT INTO ico VALUES (527, 'fa-file-powerpoint-o', NULL);
INSERT INTO ico VALUES (528, 'fa-file-sound-o', NULL);
INSERT INTO ico VALUES (529, 'fa-file-text', NULL);
INSERT INTO ico VALUES (530, 'fa-file-text-o', NULL);
INSERT INTO ico VALUES (531, 'fa-file-video-o', NULL);
INSERT INTO ico VALUES (532, 'fa-file-word-o', NULL);
INSERT INTO ico VALUES (533, 'fa-file-zip-o', NULL);
INSERT INTO ico VALUES (535, 'fa-circle-o-notch', NULL);
INSERT INTO ico VALUES (536, 'fa-cog', NULL);
INSERT INTO ico VALUES (537, 'fa-gear', NULL);
INSERT INTO ico VALUES (538, 'fa-refresh', NULL);
INSERT INTO ico VALUES (539, 'fa-spinner', NULL);
INSERT INTO ico VALUES (540, 'fa-check-square', NULL);
INSERT INTO ico VALUES (541, 'fa-check-square-o', NULL);
INSERT INTO ico VALUES (542, 'fa-circle', NULL);
INSERT INTO ico VALUES (543, 'fa-circle-o', NULL);
INSERT INTO ico VALUES (544, 'fa-dot-circle-o', NULL);
INSERT INTO ico VALUES (545, 'fa-minus-square', NULL);
INSERT INTO ico VALUES (546, 'fa-minus-square-o', NULL);
INSERT INTO ico VALUES (547, 'fa-plus-square', NULL);
INSERT INTO ico VALUES (548, 'fa-plus-square-o', NULL);
INSERT INTO ico VALUES (549, 'fa-square', NULL);
INSERT INTO ico VALUES (550, 'fa-square-o', NULL);
INSERT INTO ico VALUES (551, 'fa-cc-amex', NULL);
INSERT INTO ico VALUES (552, 'fa-cc-diners-club', NULL);
INSERT INTO ico VALUES (553, 'fa-cc-discover', NULL);
INSERT INTO ico VALUES (554, 'fa-cc-jcb', NULL);
INSERT INTO ico VALUES (555, 'fa-cc-mastercard', NULL);
INSERT INTO ico VALUES (556, 'fa-cc-paypal', NULL);
INSERT INTO ico VALUES (557, 'fa-cc-stripe', NULL);
INSERT INTO ico VALUES (558, 'fa-cc-visa', NULL);
INSERT INTO ico VALUES (559, 'fa-credit-card', NULL);
INSERT INTO ico VALUES (560, 'fa-credit-card-alt', NULL);
INSERT INTO ico VALUES (561, 'fa-google-wallet', NULL);
INSERT INTO ico VALUES (562, 'fa-paypal', NULL);
INSERT INTO ico VALUES (563, 'fa-area-chart', NULL);
INSERT INTO ico VALUES (564, 'fa-bar-chart', NULL);
INSERT INTO ico VALUES (565, 'fa-bar-chart-o', NULL);
INSERT INTO ico VALUES (566, 'fa-line-chart', NULL);
INSERT INTO ico VALUES (567, 'fa-pie-chart', NULL);
INSERT INTO ico VALUES (568, 'fa-bitcoin', NULL);
INSERT INTO ico VALUES (569, 'fa-btc', NULL);
INSERT INTO ico VALUES (570, 'fa-cny', NULL);
INSERT INTO ico VALUES (571, 'fa-dollar', NULL);
INSERT INTO ico VALUES (572, 'fa-eur', NULL);
INSERT INTO ico VALUES (573, 'fa-euro', NULL);
INSERT INTO ico VALUES (574, 'fa-gbp', NULL);
INSERT INTO ico VALUES (575, 'fa-gg', NULL);
INSERT INTO ico VALUES (576, 'fa-gg-circle', NULL);
INSERT INTO ico VALUES (577, 'fa-ils', NULL);
INSERT INTO ico VALUES (578, 'fa-inr', NULL);
INSERT INTO ico VALUES (579, 'fa-jpy', NULL);
INSERT INTO ico VALUES (580, 'fa-krw', NULL);
INSERT INTO ico VALUES (581, 'fa-money', NULL);
INSERT INTO ico VALUES (582, 'fa-rmb', NULL);
INSERT INTO ico VALUES (583, 'fa-rouble', NULL);
INSERT INTO ico VALUES (584, 'fa-rub', NULL);
INSERT INTO ico VALUES (585, 'fa-ruble', NULL);
INSERT INTO ico VALUES (586, 'fa-rupee', NULL);
INSERT INTO ico VALUES (587, 'fa-shekel', NULL);
INSERT INTO ico VALUES (588, 'fa-sheqel', NULL);
INSERT INTO ico VALUES (589, 'fa-try', NULL);
INSERT INTO ico VALUES (590, 'fa-turkish-lira', NULL);
INSERT INTO ico VALUES (591, 'fa-usd', NULL);
INSERT INTO ico VALUES (592, 'fa-won', NULL);
INSERT INTO ico VALUES (593, 'fa-yen', NULL);
INSERT INTO ico VALUES (594, 'fa-align-center', NULL);
INSERT INTO ico VALUES (595, 'fa-align-justify', NULL);
INSERT INTO ico VALUES (596, 'fa-align-left', NULL);
INSERT INTO ico VALUES (597, 'fa-align-right', NULL);
INSERT INTO ico VALUES (598, 'fa-bold', NULL);
INSERT INTO ico VALUES (599, 'fa-chain', NULL);
INSERT INTO ico VALUES (600, 'fa-chain-broken', NULL);
INSERT INTO ico VALUES (601, 'fa-clipboard', NULL);
INSERT INTO ico VALUES (602, 'fa-columns', NULL);
INSERT INTO ico VALUES (603, 'fa-copy', NULL);
INSERT INTO ico VALUES (604, 'fa-cut', NULL);
INSERT INTO ico VALUES (605, 'fa-dedent', NULL);
INSERT INTO ico VALUES (606, 'fa-eraser', NULL);
INSERT INTO ico VALUES (607, 'fa-file', NULL);
INSERT INTO ico VALUES (608, 'fa-file-o', NULL);
INSERT INTO ico VALUES (609, 'fa-file-text', NULL);
INSERT INTO ico VALUES (610, 'fa-file-text-o', NULL);
INSERT INTO ico VALUES (611, 'fa-files-o', NULL);
INSERT INTO ico VALUES (612, 'fa-floppy-o', NULL);
INSERT INTO ico VALUES (613, 'fa-font', NULL);
INSERT INTO ico VALUES (614, 'fa-header', NULL);
INSERT INTO ico VALUES (615, 'fa-indent', NULL);
INSERT INTO ico VALUES (616, 'fa-italic', NULL);
INSERT INTO ico VALUES (617, 'fa-link', NULL);
INSERT INTO ico VALUES (618, 'fa-list', NULL);
INSERT INTO ico VALUES (619, 'fa-list-alt', NULL);
INSERT INTO ico VALUES (620, 'fa-list-ol', NULL);
INSERT INTO ico VALUES (621, 'fa-list-ul', NULL);
INSERT INTO ico VALUES (622, 'fa-outdent', NULL);
INSERT INTO ico VALUES (623, 'fa-paperclip', NULL);
INSERT INTO ico VALUES (624, 'fa-paragraph', NULL);
INSERT INTO ico VALUES (625, 'fa-paste', NULL);
INSERT INTO ico VALUES (626, 'fa-repeat', NULL);
INSERT INTO ico VALUES (627, 'fa-rotate-left', NULL);
INSERT INTO ico VALUES (628, 'fa-rotate-right', NULL);
INSERT INTO ico VALUES (629, 'fa-save', NULL);
INSERT INTO ico VALUES (630, 'fa-scissors', NULL);
INSERT INTO ico VALUES (631, 'fa-strikethrough', NULL);
INSERT INTO ico VALUES (632, 'fa-subscript', NULL);
INSERT INTO ico VALUES (633, 'fa-superscript', NULL);
INSERT INTO ico VALUES (634, 'fa-table', NULL);
INSERT INTO ico VALUES (635, 'fa-text-height', NULL);
INSERT INTO ico VALUES (636, 'fa-text-width', NULL);
INSERT INTO ico VALUES (637, 'fa-th', NULL);
INSERT INTO ico VALUES (638, 'fa-th-large', NULL);
INSERT INTO ico VALUES (639, 'fa-th-list', NULL);
INSERT INTO ico VALUES (640, 'fa-underline', NULL);
INSERT INTO ico VALUES (641, 'fa-undo', NULL);
INSERT INTO ico VALUES (642, 'fa-unlink', NULL);
INSERT INTO ico VALUES (643, 'fa-angle-double-down', NULL);
INSERT INTO ico VALUES (644, 'fa-angle-double-left', NULL);
INSERT INTO ico VALUES (645, 'fa-angle-double-right', NULL);
INSERT INTO ico VALUES (646, 'fa-angle-double-up', NULL);
INSERT INTO ico VALUES (647, 'fa-angle-down', NULL);
INSERT INTO ico VALUES (648, 'fa-angle-left', NULL);
INSERT INTO ico VALUES (649, 'fa-angle-right', NULL);
INSERT INTO ico VALUES (650, 'fa-angle-up', NULL);
INSERT INTO ico VALUES (651, 'fa-arrow-circle-down', NULL);
INSERT INTO ico VALUES (652, 'fa-arrow-circle-left', NULL);
INSERT INTO ico VALUES (653, 'fa-arrow-circle-o-down', NULL);
INSERT INTO ico VALUES (654, 'fa-arrow-circle-o-left', NULL);
INSERT INTO ico VALUES (655, 'fa-arrow-circle-o-right', NULL);
INSERT INTO ico VALUES (656, 'fa-arrow-circle-o-up', NULL);
INSERT INTO ico VALUES (657, 'fa-arrow-circle-right', NULL);
INSERT INTO ico VALUES (658, 'fa-arrow-circle-up', NULL);
INSERT INTO ico VALUES (659, 'fa-arrow-down', NULL);
INSERT INTO ico VALUES (660, 'fa-arrow-left', NULL);
INSERT INTO ico VALUES (661, 'fa-arrow-right', NULL);
INSERT INTO ico VALUES (662, 'fa-arrow-up', NULL);
INSERT INTO ico VALUES (663, 'fa-arrows', NULL);
INSERT INTO ico VALUES (664, 'fa-arrows-alt', NULL);
INSERT INTO ico VALUES (665, 'fa-arrows-h', NULL);
INSERT INTO ico VALUES (666, 'fa-arrows-v', NULL);
INSERT INTO ico VALUES (667, 'fa-caret-down', NULL);
INSERT INTO ico VALUES (668, 'fa-caret-left', NULL);
INSERT INTO ico VALUES (669, 'fa-caret-right', NULL);
INSERT INTO ico VALUES (670, 'fa-caret-square-o-down', NULL);
INSERT INTO ico VALUES (671, 'fa-caret-square-o-left', NULL);
INSERT INTO ico VALUES (672, 'fa-caret-square-o-right', NULL);
INSERT INTO ico VALUES (673, 'fa-caret-square-o-up', NULL);
INSERT INTO ico VALUES (674, 'fa-caret-up', NULL);
INSERT INTO ico VALUES (675, 'fa-chevron-circle-down', NULL);
INSERT INTO ico VALUES (676, 'fa-chevron-circle-left', NULL);
INSERT INTO ico VALUES (677, 'fa-chevron-circle-right', NULL);
INSERT INTO ico VALUES (678, 'fa-chevron-circle-up', NULL);
INSERT INTO ico VALUES (679, 'fa-chevron-down', NULL);
INSERT INTO ico VALUES (680, 'fa-chevron-left', NULL);
INSERT INTO ico VALUES (681, 'fa-chevron-right', NULL);
INSERT INTO ico VALUES (682, 'fa-chevron-up', NULL);
INSERT INTO ico VALUES (683, 'fa-exchange', NULL);
INSERT INTO ico VALUES (684, 'fa-hand-o-down', NULL);
INSERT INTO ico VALUES (685, 'fa-hand-o-left', NULL);
INSERT INTO ico VALUES (686, 'fa-hand-o-right', NULL);
INSERT INTO ico VALUES (687, 'fa-hand-o-up', NULL);
INSERT INTO ico VALUES (688, 'fa-long-arrow-down', NULL);
INSERT INTO ico VALUES (689, 'fa-long-arrow-left', NULL);
INSERT INTO ico VALUES (690, 'fa-long-arrow-right', NULL);
INSERT INTO ico VALUES (691, 'fa-long-arrow-up', NULL);
INSERT INTO ico VALUES (692, 'fa-toggle-down', NULL);
INSERT INTO ico VALUES (693, 'fa-toggle-left', NULL);
INSERT INTO ico VALUES (694, 'fa-toggle-right', NULL);
INSERT INTO ico VALUES (695, 'fa-toggle-up', NULL);
INSERT INTO ico VALUES (696, 'fa-arrows-alt', NULL);
INSERT INTO ico VALUES (697, 'fa-backward', NULL);
INSERT INTO ico VALUES (698, 'fa-compress', NULL);
INSERT INTO ico VALUES (699, 'fa-eject', NULL);
INSERT INTO ico VALUES (700, 'fa-expand', NULL);
INSERT INTO ico VALUES (701, 'fa-fast-backward', NULL);
INSERT INTO ico VALUES (702, 'fa-fast-forward', NULL);
INSERT INTO ico VALUES (703, 'fa-forward', NULL);
INSERT INTO ico VALUES (704, 'fa-pause', NULL);
INSERT INTO ico VALUES (705, 'fa-pause-circle', NULL);
INSERT INTO ico VALUES (706, 'fa-pause-circle-o', NULL);
INSERT INTO ico VALUES (707, 'fa-play', NULL);
INSERT INTO ico VALUES (708, 'fa-play-circle', NULL);
INSERT INTO ico VALUES (709, 'fa-play-circle-o', NULL);
INSERT INTO ico VALUES (710, 'fa-random', NULL);
INSERT INTO ico VALUES (711, 'fa-step-backward', NULL);
INSERT INTO ico VALUES (712, 'fa-step-forward', NULL);
INSERT INTO ico VALUES (713, 'fa-stop', NULL);
INSERT INTO ico VALUES (714, 'fa-stop-circle', NULL);
INSERT INTO ico VALUES (715, 'fa-stop-circle-o', NULL);
INSERT INTO ico VALUES (716, 'fa-youtube-play', NULL);
INSERT INTO ico VALUES (717, 'fa-500px', NULL);
INSERT INTO ico VALUES (718, 'fa-adn', NULL);
INSERT INTO ico VALUES (719, 'fa-amazon', NULL);
INSERT INTO ico VALUES (720, 'fa-android', NULL);
INSERT INTO ico VALUES (721, 'fa-angellist', NULL);
INSERT INTO ico VALUES (722, 'fa-apple', NULL);
INSERT INTO ico VALUES (723, 'fa-behance', NULL);
INSERT INTO ico VALUES (724, 'fa-behance-square', NULL);
INSERT INTO ico VALUES (725, 'fa-bitbucket', NULL);
INSERT INTO ico VALUES (726, 'fa-bitbucket-square', NULL);
INSERT INTO ico VALUES (727, 'fa-bitcoin', NULL);
INSERT INTO ico VALUES (728, 'fa-black-tie', NULL);
INSERT INTO ico VALUES (729, 'fa-bluetooth', NULL);
INSERT INTO ico VALUES (730, 'fa-bluetooth-b', NULL);
INSERT INTO ico VALUES (731, 'fa-btc', NULL);
INSERT INTO ico VALUES (732, 'fa-buysellads', NULL);
INSERT INTO ico VALUES (733, 'fa-cc-amex', NULL);
INSERT INTO ico VALUES (734, 'fa-cc-diners-club', NULL);
INSERT INTO ico VALUES (735, 'fa-cc-discover', NULL);
INSERT INTO ico VALUES (736, 'fa-cc-jcb', NULL);
INSERT INTO ico VALUES (737, 'fa-cc-mastercard', NULL);
INSERT INTO ico VALUES (738, 'fa-cc-paypal', NULL);
INSERT INTO ico VALUES (739, 'fa-cc-stripe', NULL);
INSERT INTO ico VALUES (740, 'fa-cc-visa', NULL);
INSERT INTO ico VALUES (741, 'fa-chrome', NULL);
INSERT INTO ico VALUES (742, 'fa-codepen', NULL);
INSERT INTO ico VALUES (743, 'fa-codiepie', NULL);
INSERT INTO ico VALUES (744, 'fa-connectdevelop', NULL);
INSERT INTO ico VALUES (745, 'fa-contao', NULL);
INSERT INTO ico VALUES (746, 'fa-css3', NULL);
INSERT INTO ico VALUES (747, 'fa-dashcube', NULL);
INSERT INTO ico VALUES (748, 'fa-delicious', NULL);
INSERT INTO ico VALUES (749, 'fa-deviantart', NULL);
INSERT INTO ico VALUES (750, 'fa-digg', NULL);
INSERT INTO ico VALUES (751, 'fa-dribbble', NULL);
INSERT INTO ico VALUES (752, 'fa-dropbox', NULL);
INSERT INTO ico VALUES (753, 'fa-drupal', NULL);
INSERT INTO ico VALUES (754, 'fa-edge', NULL);
INSERT INTO ico VALUES (755, 'fa-empire', NULL);
INSERT INTO ico VALUES (756, 'fa-envira', NULL);
INSERT INTO ico VALUES (757, 'fa-expeditedssl', NULL);
INSERT INTO ico VALUES (758, 'fa-fa', NULL);
INSERT INTO ico VALUES (759, 'fa-facebook', NULL);
INSERT INTO ico VALUES (760, 'fa-facebook-f', NULL);
INSERT INTO ico VALUES (761, 'fa-facebook-official', NULL);
INSERT INTO ico VALUES (762, 'fa-facebook-square', NULL);
INSERT INTO ico VALUES (763, 'fa-firefox', NULL);
INSERT INTO ico VALUES (764, 'fa-first-order', NULL);
INSERT INTO ico VALUES (765, 'fa-flickr', NULL);
INSERT INTO ico VALUES (766, 'fa-font-awesome', NULL);
INSERT INTO ico VALUES (767, 'fa-fonticons', NULL);
INSERT INTO ico VALUES (768, 'fa-fort-awesome', NULL);
INSERT INTO ico VALUES (769, 'fa-forumbee', NULL);
INSERT INTO ico VALUES (770, 'fa-foursquare', NULL);
INSERT INTO ico VALUES (771, 'fa-ge', NULL);
INSERT INTO ico VALUES (772, 'fa-get-pocket', NULL);
INSERT INTO ico VALUES (773, 'fa-gg', NULL);
INSERT INTO ico VALUES (774, 'fa-gg-circle', NULL);
INSERT INTO ico VALUES (775, 'fa-git', NULL);
INSERT INTO ico VALUES (776, 'fa-git-square', NULL);
INSERT INTO ico VALUES (777, 'fa-github', NULL);
INSERT INTO ico VALUES (778, 'fa-github-alt', NULL);
INSERT INTO ico VALUES (779, 'fa-github-square', NULL);
INSERT INTO ico VALUES (780, 'fa-gitlab', NULL);
INSERT INTO ico VALUES (781, 'fa-gittip', NULL);
INSERT INTO ico VALUES (782, 'fa-glide', NULL);
INSERT INTO ico VALUES (783, 'fa-glide-g', NULL);
INSERT INTO ico VALUES (784, 'fa-google', NULL);
INSERT INTO ico VALUES (785, 'fa-google-plus', NULL);
INSERT INTO ico VALUES (786, 'fa-google-plus-circle', NULL);
INSERT INTO ico VALUES (787, 'fa-google-plus-official', NULL);
INSERT INTO ico VALUES (788, 'fa-google-plus-square', NULL);
INSERT INTO ico VALUES (789, 'fa-google-wallet', NULL);
INSERT INTO ico VALUES (790, 'fa-gratipay', NULL);
INSERT INTO ico VALUES (791, 'fa-hacker-news', NULL);
INSERT INTO ico VALUES (792, 'fa-houzz', NULL);
INSERT INTO ico VALUES (793, 'fa-html5', NULL);
INSERT INTO ico VALUES (794, 'fa-instagram', NULL);
INSERT INTO ico VALUES (795, 'fa-internet-explorer', NULL);
INSERT INTO ico VALUES (796, 'fa-ioxhost', NULL);
INSERT INTO ico VALUES (797, 'fa-joomla', NULL);
INSERT INTO ico VALUES (798, 'fa-jsfiddle', NULL);
INSERT INTO ico VALUES (799, 'fa-lastfm', NULL);
INSERT INTO ico VALUES (800, 'fa-lastfm-square', NULL);
INSERT INTO ico VALUES (801, 'fa-leanpub', NULL);
INSERT INTO ico VALUES (802, 'fa-linkedin', NULL);
INSERT INTO ico VALUES (803, 'fa-linkedin-square', NULL);
INSERT INTO ico VALUES (804, 'fa-linux', NULL);
INSERT INTO ico VALUES (805, 'fa-maxcdn', NULL);
INSERT INTO ico VALUES (806, 'fa-meanpath', NULL);
INSERT INTO ico VALUES (807, 'fa-medium', NULL);
INSERT INTO ico VALUES (808, 'fa-mixcloud', NULL);
INSERT INTO ico VALUES (809, 'fa-modx', NULL);
INSERT INTO ico VALUES (810, 'fa-odnoklassniki', NULL);
INSERT INTO ico VALUES (811, 'fa-odnoklassniki-square', NULL);
INSERT INTO ico VALUES (812, 'fa-opencart', NULL);
INSERT INTO ico VALUES (813, 'fa-openid', NULL);
INSERT INTO ico VALUES (814, 'fa-opera', NULL);
INSERT INTO ico VALUES (815, 'fa-optin-monster', NULL);
INSERT INTO ico VALUES (816, 'fa-pagelines', NULL);
INSERT INTO ico VALUES (817, 'fa-paypal', NULL);
INSERT INTO ico VALUES (818, 'fa-pied-piper', NULL);
INSERT INTO ico VALUES (819, 'fa-pied-piper-alt', NULL);
INSERT INTO ico VALUES (820, 'fa-pied-piper-pp', NULL);
INSERT INTO ico VALUES (821, 'fa-pinterest', NULL);
INSERT INTO ico VALUES (822, 'fa-pinterest-p', NULL);
INSERT INTO ico VALUES (823, 'fa-pinterest-square', NULL);
INSERT INTO ico VALUES (824, 'fa-product-hunt', NULL);
INSERT INTO ico VALUES (825, 'fa-qq', NULL);
INSERT INTO ico VALUES (826, 'fa-ra', NULL);
INSERT INTO ico VALUES (827, 'fa-rebel', NULL);
INSERT INTO ico VALUES (828, 'fa-reddit', NULL);
INSERT INTO ico VALUES (829, 'fa-reddit-alien', NULL);
INSERT INTO ico VALUES (830, 'fa-reddit-square', NULL);
INSERT INTO ico VALUES (831, 'fa-renren', NULL);
INSERT INTO ico VALUES (832, 'fa-resistance', NULL);
INSERT INTO ico VALUES (833, 'fa-safari', NULL);
INSERT INTO ico VALUES (834, 'fa-scribd', NULL);
INSERT INTO ico VALUES (835, 'fa-sellsy', NULL);
INSERT INTO ico VALUES (836, 'fa-share-alt', NULL);
INSERT INTO ico VALUES (837, 'fa-share-alt-square', NULL);
INSERT INTO ico VALUES (838, 'fa-shirtsinbulk', NULL);
INSERT INTO ico VALUES (839, 'fa-simplybuilt', NULL);
INSERT INTO ico VALUES (840, 'fa-skyatlas', NULL);
INSERT INTO ico VALUES (841, 'fa-skype', NULL);
INSERT INTO ico VALUES (842, 'fa-slack', NULL);
INSERT INTO ico VALUES (843, 'fa-slideshare', NULL);
INSERT INTO ico VALUES (844, 'fa-snapchat', NULL);
INSERT INTO ico VALUES (845, 'fa-snapchat-ghost', NULL);
INSERT INTO ico VALUES (846, 'fa-snapchat-square', NULL);
INSERT INTO ico VALUES (847, 'fa-soundcloud', NULL);
INSERT INTO ico VALUES (848, 'fa-spotify', NULL);
INSERT INTO ico VALUES (849, 'fa-stack-exchange', NULL);
INSERT INTO ico VALUES (850, 'fa-stack-overflow', NULL);
INSERT INTO ico VALUES (851, 'fa-steam', NULL);
INSERT INTO ico VALUES (852, 'fa-steam-square', NULL);
INSERT INTO ico VALUES (853, 'fa-stumbleupon', NULL);
INSERT INTO ico VALUES (854, 'fa-stumbleupon-circle', NULL);
INSERT INTO ico VALUES (855, 'fa-tencent-weibo', NULL);
INSERT INTO ico VALUES (856, 'fa-themeisle', NULL);
INSERT INTO ico VALUES (857, 'fa-trello', NULL);
INSERT INTO ico VALUES (858, 'fa-tripadvisor', NULL);
INSERT INTO ico VALUES (859, 'fa-tumblr', NULL);
INSERT INTO ico VALUES (860, 'fa-tumblr-square', NULL);
INSERT INTO ico VALUES (861, 'fa-twitch', NULL);
INSERT INTO ico VALUES (862, 'fa-twitter', NULL);
INSERT INTO ico VALUES (863, 'fa-twitter-square', NULL);
INSERT INTO ico VALUES (864, 'fa-usb', NULL);
INSERT INTO ico VALUES (865, 'fa-viacoin', NULL);
INSERT INTO ico VALUES (866, 'fa-viadeo', NULL);
INSERT INTO ico VALUES (867, 'fa-viadeo-square', NULL);
INSERT INTO ico VALUES (868, 'fa-vimeo', NULL);
INSERT INTO ico VALUES (869, 'fa-vimeo-square', NULL);
INSERT INTO ico VALUES (870, 'fa-vine', NULL);
INSERT INTO ico VALUES (871, 'fa-vk', NULL);
INSERT INTO ico VALUES (872, 'fa-wechat', NULL);
INSERT INTO ico VALUES (873, 'fa-weibo', NULL);
INSERT INTO ico VALUES (874, 'fa-weixin', NULL);
INSERT INTO ico VALUES (875, 'fa-whatsapp', NULL);
INSERT INTO ico VALUES (876, 'fa-wikipedia-w', NULL);
INSERT INTO ico VALUES (877, 'fa-windows', NULL);
INSERT INTO ico VALUES (878, 'fa-wordpress', NULL);
INSERT INTO ico VALUES (879, 'fa-wpbeginner', NULL);
INSERT INTO ico VALUES (880, 'fa-wpforms', NULL);
INSERT INTO ico VALUES (881, 'fa-xing', NULL);
INSERT INTO ico VALUES (882, 'fa-xing-square', NULL);
INSERT INTO ico VALUES (883, 'fa-y-combinator', NULL);
INSERT INTO ico VALUES (884, 'fa-y-combinator-square', NULL);
INSERT INTO ico VALUES (885, 'fa-yahoo', NULL);
INSERT INTO ico VALUES (886, 'fa-yc', NULL);
INSERT INTO ico VALUES (887, 'fa-yc-square', NULL);
INSERT INTO ico VALUES (888, 'fa-yelp', NULL);
INSERT INTO ico VALUES (889, 'fa-yoast', NULL);
INSERT INTO ico VALUES (890, 'fa-youtube', NULL);
INSERT INTO ico VALUES (891, 'fa-youtube-play', NULL);
INSERT INTO ico VALUES (892, 'fa-youtube-square', NULL);
INSERT INTO ico VALUES (893, 'fa-ambulance', NULL);
INSERT INTO ico VALUES (894, 'fa-h-square', NULL);
INSERT INTO ico VALUES (895, 'fa-heart', NULL);
INSERT INTO ico VALUES (896, 'fa-heart-o', NULL);
INSERT INTO ico VALUES (897, 'fa-heartbeat', NULL);
INSERT INTO ico VALUES (898, 'fa-hospital-o', NULL);
INSERT INTO ico VALUES (899, 'fa-medkit', NULL);
INSERT INTO ico VALUES (900, 'fa-plus-square', NULL);
INSERT INTO ico VALUES (901, 'fa-stethoscope', NULL);
INSERT INTO ico VALUES (902, 'fa-user-md', NULL);
INSERT INTO ico VALUES (903, 'fa-wheelchair', NULL);
INSERT INTO ico VALUES (904, 'fa-wheelchair-alt', NULL);

INSERT INTO legal VALUES (1, NULL, '天津市人民政府办公厅关于印发2015年天津市大型会展论坛活动计划的通知 ', NULL, NULL, NULL);
INSERT INTO legal VALUES (2, NULL, '天津市人民政府办公厅关于印发天津市人民政府2015年度立法计划的通知 ', NULL, NULL, NULL);
INSERT INTO legal VALUES (3, NULL, '天津市人民代表大会常务委员会公示地方性法规案办法 ', NULL, NULL, NULL);
INSERT INTO legal VALUES (4, NULL, '天津市人民代表大会常务委员会关于修改《天津市制定地方性法规听证办法》的决定 ', NULL, NULL, NULL);
INSERT INTO legal VALUES (5, NULL, '天津市行政执法监督规定 ', NULL, NULL, NULL);
INSERT INTO legal VALUES (6, NULL, '	天津市人民政府关于机构设置的通知 ', NULL, NULL, NULL);
INSERT INTO legal VALUES (7, NULL, '天津市人民政府办公厅关于印发2014年政府信息公开工作要点的通知 ', NULL, NULL, NULL);

INSERT INTO legal_tree VALUES (1, NULL, '宪法类', NULL, NULL, '');
INSERT INTO legal_tree VALUES (2, 1, '宪法', NULL, NULL, '');
INSERT INTO legal_tree VALUES (3, NULL, '民商法类', NULL, NULL, '');
INSERT INTO legal_tree VALUES (4, 3, '民法', NULL, NULL, '');
INSERT INTO legal_tree VALUES (6, 1, '国家机构', NULL, NULL, '');
INSERT INTO legal_tree VALUES (7, 6, '选举法', NULL, NULL, '');
INSERT INTO legal_tree VALUES (8, 6, '组织法', NULL, NULL, '');
INSERT INTO legal_tree VALUES (9, 6, '权力机关（人大机关）', NULL, NULL, '');
INSERT INTO legal_tree VALUES (10, 6, '行政机关', NULL, NULL, '');
INSERT INTO legal_tree VALUES (11, 6, '审判机关', NULL, NULL, '');
INSERT INTO legal_tree VALUES (12, 3, '知识产权', NULL, NULL, '');
INSERT INTO legal_tree VALUES (14, 3, '婚姻家庭继承', NULL, NULL, '');
INSERT INTO legal_tree VALUES (15, 3, '债权', NULL, NULL, '');
INSERT INTO legal_tree VALUES (16, 3, '市场经济主体', NULL, NULL, '');
INSERT INTO legal_tree VALUES (17, 3, '证券、期货、债券', NULL, NULL, '');

INSERT INTO mo_info VALUES (1, '长城基金公司深圳直销中心', '直销机构', '深圳市福田区益田路6009号新世界大厦1950 B座', '黄念英', '0755-23982244', 'BROKERAGE');
INSERT INTO mo_info VALUES (2, '中国民生银行股份有限公司', NULL, '北京市西城区复兴门内大街 2 号', '赵天杰', '010-58560666', 'CUSTODIAN');
INSERT INTO mo_info VALUES (3, '中国农业银行股份有限公司', '直销机构', '北京市西城区金融街7号英蓝国际大厦1982号2栋3号290C座', '赵四', '010-58560888', 'BROKERAGE');
INSERT INTO mo_info VALUES (4, '中国建设银行股份有限公司', NULL, '上海市浦东新区浦东南路256号', '邱文勋', '021-51150756', 'CUSTODIAN');

INSERT INTO section_config VALUES (1, 10000, '第一部分 绪 言', '<p>本招募说明书依据《中华人民共和国证券投资基金法》（以下简称“《基金法》”）、《证券 投资基金信息披露管理办法》（以下简称“《信息披露办法》”）、《公开募集证券投资基金运作 管理办法》（以下简称“《运作办法》”）、《证券投资基金销售管理办法》（以下简称“《销售办 法》”）等有关法律法规及《长城新视野混合型证券投资基金基金合同》（以下简称“基金合 同”）编写。 本招募说明书阐述了长城新视野混合型证券投资基金的投资目标、策略、风险、费率 等与投资者投资决策有关的全部必要事项，投资者在做出投资决策前应仔细阅读本招募说 明书。 基金管理人承诺本招募说明书不存在任何虚假记载、误导性陈述或者重大遗漏，并对 其真实性、准确性、完整性承担法律责任。本基金是根据本招募说明书所载明的资料申请 募集的。本基金管理人没有委托或授权任何其他人提供未在本招募说明书中载明的信息， 或对本招募说明书做出任何解释或者说明。 本招募说明书根据本基金的基金合同编写，并经中国证监会注册。基金合同是约定基 金当事人之间权利、义务的法律文件。基金投资者自依基金合同取得基金份额，即成为基 金份额持有人和本基金合同的当事人，其持有基金份额的行为本身即表明其对基金合同的 承认和接受，并按照《基金法》、基金合同及其他规定享有权利、承担义务。基金投资者 欲了解基金份额持有人的权利和义务，应详细查阅本基金基金合同。 @1112<br></p>');
INSERT INTO section_config VALUES (2, 20000, '第二部分 释 义', '<div>在本招募说明书中，除非文意另有所指，下列词语或简称具有如下含义： <br> 1、基金或本基金：指长城新视野混合型证券投资基金 <br> 2、基金管理人：指长城基金管理有限公司 <br> 3、基金托管人：指中国民生银行股份有限公司 <br> 4、基金合同或本基金合同：指《长城新视野混合型证券投资基金基金合同》及对本基金合同的任何有效修订和补充 <br> 5、托管协议：指基金管理人与基金托管人就本基金签订之《长城新视野混合型证券投资基金托管协议》及对该托管协议的任何有效修订和补充 <br> 6、招募说明书：指《长城新视野混合型证券投资基金招募说明书》及其定期的更新 <br> 7、基金份额发售公告：指《长城新视野混合型证券投资基金基金份额发售公告》 <br> 8、法律法规：指中国现行有效并公布实施的法律、行政法规、规范性文件、司法解释、 行政规章以及其他对基金合同当事人有约束力的决定、决议、通知等 <br> 9、《基金法》：指《中华人民共和国证券投资基金法》及颁布机关对其不时做出的修订 <br> 10、《销售办法》：指《证券投资基金销售管理办法》及颁布机关对其不时做出的修订 <br> 11、《信息披露办法》：指《证券投资基金信息披露管理办法》及颁布机关对其不时做 出的修订 <br> 12、《运作办法》：指《公开募集证券投资基金运作管理办法》及颁布机关对其不时做出的修订 <br> 13、中国证监会：指中国证券监督管理委员会 <br> 14、银行业监督管理机构：指中国人民银行和/或中国银行业监督管理委员会 <br> 15、基金合同当事人：指受基金合同约束，根据基金合同享有权利并承担义务的法律主 体，包括基金管理人、基金托管人和基金份额持有人 <br> 16、个人投资者：指依据有关法律法规规定可投资于证券投资基金的自然人 <br> 17、机构投资者：指依法可以投资证券投资基金的、在中华人民共和国境内合法登记并 存续或经有关政府部门批准设立并存续的企业法人、事业法人、社会团体或其他组织 <br> 18、合格境外机构投资者：指符合《合格境外机构投资者境内证券投资管理办法》及相 关法律法规规定可以投资于在中国境内依法募集的证券投资基金的中国境外的机构投资者 <br> 19、投资人：指个人投资者、机构投资者和合格境外机构投资者以及法律法规或中国证 监会允许购买证券投资基金的其他投资人的合称 <br> 20、基金份额持有人：指依基金合同和招募说明书合法取得基金份额的投资人 <br> 21、基金销售业务：指基金管理人或销售机构宣传推介基金，发售基金份额，办理基金份额的申购、赎回、转换、非交易过户、转托管及定期定额投资等业务。 <br> 22、销售机构：指长城基金管理有限公司以及符合《销售办法》和中国证监会规定的其他条件，取得基金销售业务资格并与基金管理人签订了基金销售服务代理协议，代为办理基金销售业务的机构 <br> 23、直销机构：指长城基金管理有限公司 <br> 24、代销机构：指符合《销售办法》和中国证监会规定的其他条件，取得基金代销业务 资格并与基金管理人签订了基金销售服务代理协议，代为办理基金销售业务的机构 <br> 25、基金销售网点：指直销机构的直销中心及代销机构的代销网点 <br> 26、登记业务：指基金登记、存管、过户、清算和结算业务，具体内容包括投资人基金账户的建立和管理、基金份额登记、基金销售业务的确认、清算和结算、代理发放红利、建立并保管基金份额 持有人名册和办理非交易过户等 <br> 27、登记机构：指办理登记业务的机构。基金的登记机构为长城基金管理有限公司或接 受长城基金管理有限公司委托代为办理登记业务的机构 <br> 28、基金账户：指登记机构为投资人开立的、记录其持有的、基金管理人所管理的基金 份额余额及其变动情况的账户 <br> 29、基金交易账户：指销售机构为投资人开立的、记录投资人通过该销售机构买卖基金 的基金份额变动及结余情况的账户 <br> 30、基金合同生效日：指基金募集达到法律法规规定及基金合同规定的条件，基金管理 人向中国证监会办理基金备案手续完毕，并获得中国证监会书面确认的日期 <br> 31、基金合同终止日：指基金合同规定的基金合同终止事由出现后，基金财产清算完毕， 清算结果报中国证监会备案并予以公告的日期 <br> 32、基金募集期：指自基金份额发售之日起至发售结束之日止的期间，最长不得超过三 个月 <br> 33、存续期：指基金合同生效至终止之间的不定期期限 <br> 34、工作日：指上海证券交易所、深圳证券交易所的正常交易日<br> 35、T 日：指销售机构在规定时间受理投资人申购、赎回或其他业务申请的开放日 <br> 36、T+n 日：指自 T 日起第 n 个工作日(不包含 T 日) <br> 37、开放日：指为投资人办理基金份额申购、赎回或其他业务的工作日 <br> 38、开放时间：指开放日基金接受申购、赎回或其他交易的时间段 <br> 39、《业务规则》：指长城基金管理有限公司开放式基金业务规则，是规范基金管理人所管理的开放式证券投资基金登记方面的业务规则，由基金管理人和投资人共同遵守 <br> 40、认购：指在基金募集期内，投资人申请购买基金份额的行为 <br> 41、申购：指基金合同生效后，投资人根据基金合同和招募说明书的规定申请购买基金 份额的行为 <br> 42、赎回：指基金合同生效后，基金份额持有人按基金合同规定的条件要求将基金份额 兑换为现金的行为 <br> 43、基金转换：指基金份额持有人按照本基金合同和基金管理人届时有效公告规定的条 件，申请将其持有基金管理人管理的、某一基金的基金份额转换为基金管理人管理的其他基金基金份额的行为 <br> 44、转托管：指基金份额持有人在本基金的不同销售机构之间实施的变更所持基金份额 销售机构的操作 <br> 45、定期定额投资计划：指投资人通过有关销售机构提出申请，约定每期申购日、扣款 金额及扣款方式，由销售机构于每期约定扣款日在投资人指定银行账户内自动完成扣款及基金申购申请的一种投资方式 <br> 46、巨额赎回：指本基金单个开放日，基金净赎回申请(赎回申请份额总数加上基金转换中转出申请份额总数后扣除申购申请份额总数及基金转换中转入申请份额总数后的余额)超过上一开放日基金总份额的 10% <br> 47、元：指人民币元 <br> 48、基金收益：指基金投资所得红利、股息、债券利息、买卖证券价差、银行存款利息、 已实现的其他合法收入及因运用基金财产带来的成本和费用的节约 <br> 49、基金资产总值：指基金拥有的各类有价证券、银行存款本息、基金应收申购款及其他资产的价值总和 <br> 50、基金资产净值：指基金资产总值减去基金负债后的价值\n51、基金份额净值：指计算日基金资产净值除以计算日基金份额总数 <br> 52、基金资产估值：指计算评估基金资产和负债的价值，以确定基金资产净值和基金份额净值的过程 <br> 53、指定媒介：指中国证监会指定的用以进行信息披露的报刊、互联网网站及其他媒介\n</div><div>54、不可抗力：指本合同当事人不能预见、不能避免且不能克服的客观事件</div><p><br></p>');

INSERT INTO ugroup VALUES (1, '管理员', 'Admin', 'ROLE');
INSERT INTO ugroup VALUES (2, '普通用户', 'User', 'ROLE');
INSERT INTO ugroup VALUES (3, '人事部', 'Personnel', 'DEPARTMENT');
INSERT INTO ugroup VALUES (4, '财务部', 'Financial', 'DEPARTMENT');
INSERT INTO ugroup VALUES (5, 'IT部', 'Technology', 'DEPARTMENT');
INSERT INTO ugroup VALUES (6, '助理', 'Assistant', 'POSITION');
INSERT INTO ugroup VALUES (7, '主管', 'Director', 'POSITION');
INSERT INTO ugroup VALUES (8, '经理', 'Manager', 'POSITION');
INSERT INTO ugroup VALUES (9, '员工', 'Employee', 'POSITION');
INSERT INTO ugroup VALUES (10, '董事长', 'CEO', 'POSITION');
INSERT INTO ugroup VALUES (37, '审核人员', 'Audit', 'ROLE');

INSERT INTO usergroup VALUES (1, 1);
INSERT INTO usergroup VALUES (2, 1);
INSERT INTO usergroup VALUES (15, 37);

insert into ztree (ID, ICO, NAME, NODE, POSITION, ROLE, TITLE, URL, PARENTID, MENUTYPE) values (120, 'fa-list', '菜单配置', 1200000, null, null, '菜单配置', '/admin/menus', 47, null);
insert into ztree (ID, ICO, NAME, NODE, POSITION, ROLE, TITLE, URL, PARENTID, MENUTYPE) values (10, '     fa-home', '首页', 100000, 'Manager', 'User', '首页', '/app/index', null, 1);
insert into ztree (ID, ICO, NAME, NODE, POSITION, ROLE, TITLE, URL, PARENTID, MENUTYPE) values (13, 'fa-file-text-o', '招募说明书更新', 180000, 'Manager', 'User', '招募说明书更新', 'report', 14, 1);
insert into ztree (ID, ICO, NAME, NODE, POSITION, ROLE, TITLE, URL, PARENTID, MENUTYPE) values (14, ' fa-files-o', '文档模板管理', 140000, 'Manager', 'User', '文档模板管理', null, null, 1);
insert into ztree (ID, ICO, NAME, NODE, POSITION, ROLE, TITLE, URL, PARENTID, MENUTYPE) values (15, 'fa-file-powerpoint-o', '报告配置', 155000, 'Manager', 'User', '报告配置', 'contract', 14, null);
insert into ztree (ID, ICO, NAME, NODE, POSITION, ROLE, TITLE, URL, PARENTID, MENUTYPE) values (16, ' fa-file-text', '模板元素维护', 160000, 'Manager', 'User', '模板元素维护', '/audit/sectionConfig', 14, 1);
insert into ztree (ID, ICO, NAME, NODE, POSITION, ROLE, TITLE, URL, PARENTID, MENUTYPE) values (20, ' fa-dropbox', '机构信息维护', 200000, 'Manager', 'User', '机构信息维护', null, null, 1);
insert into ztree (ID, ICO, NAME, NODE, POSITION, ROLE, TITLE, URL, PARENTID, MENUTYPE) values (21, 'fa-hand-o-right', '管理人信息维护', 210000, 'Manager', 'User', '管理人信息维护', 'adminis', 20, 1);
insert into ztree (ID, ICO, NAME, NODE, POSITION, ROLE, TITLE, URL, PARENTID, MENUTYPE) values (22, 'fa-paypal', '基金经理信息维护', 220000, 'Manager', 'User', '基金经理信息维护', '/audit/fundManagers', 20, 1);
insert into ztree (ID, ICO, NAME, NODE, POSITION, ROLE, TITLE, URL, PARENTID, MENUTYPE) values (23, ' fa-hospital-o', '托管人信息维护', 230000, 'Manager', 'User', '托管人信息维护', '/audit/custodian', 20, 1);
insert into ztree (ID, ICO, NAME, NODE, POSITION, ROLE, TITLE, URL, PARENTID, MENUTYPE) values (24, ' fa-gittip', '销售机构信息维护', 240000, 'Manager', 'User', '销售机构信息维护', '/audit/brokerage', 20, 1);
insert into ztree (ID, ICO, NAME, NODE, POSITION, ROLE, TITLE, URL, PARENTID, MENUTYPE) values (25, 'fa-glide-g', '申购赎回费率维护', 250000, 'Manager', 'User', '申购赎回费率维护', 'rates', 20, 1);
insert into ztree (ID, ICO, NAME, NODE, POSITION, ROLE, TITLE, URL, PARENTID, MENUTYPE) values (47, 'fa-gg-circle', '系统管理', 805000, 'Manager', 'Admin', '系统管理', null, null, 1);
insert into ztree (ID, ICO, NAME, NODE, POSITION, ROLE, TITLE, URL, PARENTID, MENUTYPE) values (49, 'fa-github-alt', '用户维护', 490000, 'Manager', 'Admin', '用户管理', '/admin/users', 47, 1);
insert into ztree (ID, ICO, NAME, NODE, POSITION, ROLE, TITLE, URL, PARENTID, MENUTYPE) values (50, 'fa-puzzle-piece', '部门维护', 500000, 'Manager', 'Admin', '用户组管理', '/admin/department', 47, 1);
insert into ztree (ID, ICO, NAME, NODE, POSITION, ROLE, TITLE, URL, PARENTID, MENUTYPE) values (52, 'fa-inbox', '角色维护', 520000, 'Manager', 'Admin', '角色维护', '/admin/role', 47, 1);
insert into ztree (ID, ICO, NAME, NODE, POSITION, ROLE, TITLE, URL, PARENTID, MENUTYPE) values (53, 'fa-sitemap', '菜单配置', 530000, 'Manager', 'Admin', '菜单配置', '/admin/menus', 47, 1);
insert into ztree (ID, ICO, NAME, NODE, POSITION, ROLE, TITLE, URL, PARENTID, MENUTYPE) values (56, 'fa-hospital-o', '操作日志', 560000, 'Manager', 'Admin', '操作日志', '/app/logs', 47, 1);
insert into ztree (ID, ICO, NAME, NODE, POSITION, ROLE, TITLE, URL, PARENTID, MENUTYPE) values (70, 'fa-file-code-o', '临时公告查询', 700000, 'Manager', 'User', '临时公告查询', 'files', null, 1);
insert into ztree (ID, ICO, NAME, NODE, POSITION, ROLE, TITLE, URL, PARENTID, MENUTYPE) values (80, 'fa-first-order', '法律法规库', 800000, null, null, '法律法规库', null, null, null);
insert into ztree (ID, ICO, NAME, NODE, POSITION, ROLE, TITLE, URL, PARENTID, MENUTYPE) values (81, ' fa-universal-access', '事件检索', 810000, null, null, '事件检索', '/audit/eventRetrieval', 80, null);
insert into ztree (ID, ICO, NAME, NODE, POSITION, ROLE, TITLE, URL, PARENTID, MENUTYPE) values (82, '  fa-themeisle', '法规维护', 820000, null, null, '法规维护', '/audit/legalConfig', 80, null);
insert into ztree (ID, ICO, NAME, NODE, POSITION, ROLE, TITLE, URL, PARENTID, MENUTYPE) values (84, 'fa-instagram', '标签库', 1010000, null, null, '标签库', '/audit/', 80, null);
